Supported new mode: SCREEN_ANIMATION
collab-project/videojs-record pull request #531
Opened 2020-12-24 06:46 UTC by mayank1513

Hi,

I realized that screen could only be captured as video and not as animated gif. Thus, I added a new mode. No changes in the options object.

Earlier, if options object contained `animated: true`, `screen` option would be ignored. Now, by default screen is recorded as video but one can override this by adding animation options to turn it into `gif`. 

Hope this helps.

2020-12-26 16:53 UTC, thijstriemstra requested changes
thanks! can you revert the whitespace changes in this pull request? and add an entry to the changelog?

2020-12-26 16:53 UTC, thijstriemstra commented on src/js/engine/record-mode.js
> + * @since 4.1.1
no need to change this.

2020-12-26 16:53 UTC, thijstriemstra commented on package-lock.json
>        "dev": true
can you revert the changes to package-lock.json as well

2020-12-27 04:36 UTC, mayank1513 commented
Hi,

I will do it as soon as possible. and also respond to your other email
regarding the issue as soon as possible. Little busy today.

Mayank Kumar Chaudhari


On Sat, Dec 26, 2020 at 10:24 PM Thijs Triemstra <notifications@github.com>
wrote:

> *@thijstriemstra* commented on this pull request.
> ------------------------------
>
> In package-lock.json
> <https://github.com/collab-project/videojs-record/pull/531#discussion_r549010488>
> :
>
> > @@ -2592,9 +2592,9 @@
>        "dev": true
>
> can you revert the changes to package-lock.json as well
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/collab-project/videojs-record/pull/531#pullrequestreview-558882557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGCR4VJYU6KS5L5MFHJM5BDSWYIKZANCNFSM4VH3VP5Q>
> .
>

2021-01-03 02:46 UTC, mayank1513 commented
Hi, sorry for delay. I am not able to create a new pull request now.

2021-02-01 20:32 UTC, thijstriemstra commented
thanks for the pull request @mayank1513. While it's a good suggestion, I'd rather not expand on the old, buggy gif-recorder currently used in videojs-record to create animated GIFs. I started a new implementation, using gifshot (#292), but ran into other issues and the fact that that library is also not maintained anymore. Eventually we'll find a better implementation but I'm hesitant to build new things on top of the gif-recorder... thoughts?

2023-09-10 11:22 UTC, closed without merging