Stop screensharing on microphone permissions error in AUDIO_SCREEN mode
collab-project/videojs-record pull request #585
Opened 2021-06-09 12:37 UTC by RomanMukhin

WHEN the AUDIO_SCREEN mode is selected
AND screen sharing is allowed
AND microphone is not allowed
THEN screen sharing continues despite the fact that "device error" event is triggered (not "device ready")

Expected: screen sharing stream is closed and the device error event is triggered

2021-06-09 12:52 UTC, thijstriemstra requested changes
thanks @RomanMukhin

does this happen in other screen sharing modes as well?

can you also add a changelog entry?

2021-06-09 12:58 UTC, thijstriemstra commented on CHANGES.md
> +- Stop screen sharing on a microphone permissions error in the AUDIO_SCREEN mode
please add the pull request nr as well

2021-06-09 12:59 UTC, thijstriemstra commented on src/js/videojs.record.js
> +                        if (screenStream.active) {
add a comment why this check is added, e.g. permissions error. more info is better.

2021-06-09 13:00 UTC, RomanMukhin commented
@thijstriemstra added entry to changelog. This happens only in AUDIO_SCREEN since it's the only place where navigator.mediaDevices.getDisplayMedia promise is chained with navigator.mediaDevices.getUserMedia promise

2021-06-12 19:18 UTC, thijstriemstra approved these changes
thanks!

2021-06-12 19:18 UTC, merged